version: '3.8'

services:
  db:
    image: postgres:16
    container_name: lab3_postgres
    environment:
      POSTGRES_DB: magasin
      POSTGRES_USER: magasin_user
      POSTGRES_PASSWORD: magasinpswd
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: lab3_api
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/magasin
      SPRING_DATASOURCE_USERNAME: magasin_user
      SPRING_DATASOURCE_PASSWORD: magasinpswd
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"

volumes:
  db_data: